### ISSUE TITLE
Turn on debug for a service account.

### ISSUE THREAD

**Issue by startswithaj** [firebase/firebase-token-generator-php#23]
Hi Guys,

I've been migrating to firebase 3.0 today. 

I had some end to end tests using fb 2.0 running with the client sdk inside of mocha on the cli.
For testing purposes I would simply generate a token for the user I wanted to test against and turn on debugging so I could see what the problem was with any reads or writes I was doing.

I upgraded to fb 3 today and I see that the FB sdk when run on the server does not allows normal authentication methods and you must use a service account.

So I generated a service account and im using databaseAuthVariableOverride {uid: "blah"} to spoof the user I want the tests run as. But I no longer have debug for that user.

I can't find any mention in the docs about how to turn this on for a service account.

I tried to do databaseAuthVariableOverride {uid: 'blah, debug: true"} but that didn;t seem to work.

Any help is appreciated

**Comment by mikelehen** [comment]
Hey @startswithaj, thanks for the feedback.  Right now there's no way to enable the debug logging with the 3.x SDK, so if you're relying on this, you'll need to stick with the 2.x SDK.  Can I ask what your use case is?  Is it just informational logging or are you using it in some deeper way?  Thanks!

**Comment by startswithaj** [comment]
Hey @mikelehen appreciate your response. I know you guys must be busy atm.

I pretty much use it to tell why my write tests fail specifically. (I parse out the failing rule).

It is particularly helpful when writing new rules. It would be epic to be able subscribe to this output from the Node SDK, from within mocha or any node proc.

I'm sure you can appreciate, optimally you want to be writing/changing rules against tests. Not writing them and testing them in your client. 

To get around this I could run mocha in a browser which would enable me to auth with a custom token but again in a perfect world the server could get access to these logs.

**Comment by katowulf** [comment]
> WARNING: This token generator is compatible with versions 1.x.x and 2.x.x of the Firebase SDK. If you are using the 3.x.x SDK, please refer to the documentation [here](https://firebase.google.com/docs/auth/admin/#use_a_jwt_library).
