### ISSUE TITLE
Version 3.0.0 and app secrets

### ISSUE THREAD

**Issue by calebbrewer** [firebase/firebase-token-generator-php#24]
It looks like Firebase Version 3.0.0 no longer supports app secrets. Is this true? If not how do I get my app secret when using Version 3.0.0?

**Comment by dmastag** [comment]
I got this error when using this lib

> The custom token format is incorrect. Please check the documentation

After some searching around, it seems that for firebase3 you have to use https://github.com/firebase/php-jwt

Documentation/Example is at
https://firebase.google.com/docs/auth/server#use_a_jwt_library

**Comment by katowulf** [comment]
> WARNING: This token generator is compatible with versions 1.x.x and 2.x.x of the Firebase SDK. If you are using the 3.x.x SDK, please refer to the documentation [here](https://firebase.google.com/docs/auth/admin/#use_a_jwt_library).
