### ISSUE TITLE
No PHP code for firebase Cloud Messaging

### ISSUE THREAD

**Issue by iamrajendra** [firebase/firebase-token-generator-php#26]
I   am **trying  Firebase  cloud messaging for android** and for sever side I am using **PHP**. But I did not find any SDK or example for PHP developers. Like We had PHP SDK in Parse. 
Kindly take this concern seriously and do something for PHP devlopers.

**Comment by abehaskins** [comment]
Hi! You can definitely use FCM from PHP since it's just a normal HTTP call. Check out the [FCM docs on sending messages](https://firebase.google.com/docs/cloud-messaging/send-message). 

However since this isn't related to this library, I'm closing this issue!

Best,
abe
