### ISSUE TITLE
Issue while using RS256 algorithm

### ISSUE THREAD

**Issue by amolchakane** [firebase/firebase-token-generator-php#27]
According to updated Firebase docs, we have to use RS256 to sign JWT. 
So I simply changed algorithm from HS256 to RS256. But I get following exception.

**OpenSSL unable to sign data**
When I checked logs I can see PHP warning, OpenSSL unable to sign data.
`openssl_sign(): supplied key param cannot be coerced into a private key`

I Googled, but couldn't find the solution.

Please help.

**Comment by redgenie** [comment]
+1

**Comment by myuseringithub** [comment]
Yep same here. Using the recommended JWT https://github.com/firebase/php-jwt with RS256 produces the same error. 

PHP Warning:  openssl_sign(): supplied key param cannot be coerced into a private key in ...
PHP Fatal error:  Uncaught exception 'DomainException' with message 'OpenSSL unable to sign data' ...

**Comment by myuseringithub** [comment]
Solution - http://stackoverflow.com/questions/37801444/setting-up-firebase-v3-custom-auth-with-php/38002277#38002277

**Comment by katowulf** [comment]
V3 auth process is documented [here](https://firebase.google.com/docs/auth/admin/#use_a_jwt_library). This repo does not apply:

> WARNING: This token generator is compatible with versions 1.x.x and 2.x.x of the Firebase SDK. If you are using the 3.x.x SDK, please refer to the documentation [here](https://firebase.google.com/docs/auth/admin/#use_a_jwt_library).
