### ISSUE TITLE
Couldnt sign in through custom token generator

### ISSUE THREAD

**Issue by parthjdabhi** [firebase/firebase-token-generator-php#30]
How i generating token (PHP) : 
`use Firebase\Token\TokenException;
use Firebase\Token\TokenGenerator;

try {
    $generator = new TokenGenerator('<MY_FIREBASE_SECRET>');
    $token = $generator
        ->setData(array('uid' => 'xxxxosGCU8cKHNbxhnV3Gzswxxxx'))
        ->create();
} catch (TokenException $e) {
    echo "Error: ".$e->getMessage();
}

echo $token;`

I got token successfully and tying to verify in iOS side (Swift) :
`FIRAuth.auth()?.signInWithCustomToken("XXX0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhZG1pbiI6ZmFsc2UsImRlYnVnIjpmYWxzZSwiZCI6eyJ1aWQiOiJrN2Jjb3NHQ1U4Y0tITmJ4aG5WM0d6c3cwNXIxIn0sInYiOjAsImlhdCI6MTQ3MTY5OTcyNH0.v555te35unXXXvh1cL7_mbdstylOhmclQtHpzHDiXXX") { (user, error) in
            print(user)
            print(error)
        }`

Error : Error Domain=FIRAuthErrorDomain Code=17000 "The custom token format is incorrect. Please check the documentation." UserInfo={NSLocalizedDescription=The custom token format is incorrect. Please check the documentation., error_name=ERROR_INVALID_CUSTOM_TOKEN}

if i am doing any think wrong or any one can help me to catch where is problem.

Thank you
Parth Dabhi

**Comment by kiwo12345** [comment]
@parthjdabhi I have the same problem, have you found out anything?

**Comment by jeromegamez** [comment]
Just in case: If you are using a Google Service Account to authenticate your Application with Firebase, you can't use the custom tokens generated with this library anymore.

**Comment by elbuenyuz** [comment]
so what you can use?

**Comment by kiwo12345** [comment]
@elbuenyuz https://github.com/firebase/php-jwt works

**Comment by katowulf** [comment]
That code looks specific to the 3.x SDKs. Note first line of the docs in this repo: 

> WARNING: This token generator is compatible with versions 1.x.x and 2.x.x of the Firebase SDK. If you are using the 3.x.x SDK, please refer to the documentation [here](https://firebase.google.com/docs/auth/admin/#use_a_jwt_library).
